spring:
   datasource:
      # useSSL=false  表示不使用加密通讯，本机的数据库没有必要加密
      # serverTimezone=CST 表示指定服务器的时区，CST=China Standard Time
      url: jdbc:mysql://127.0.0.1:3306/weixin_kaifa_qap?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: weixin
      password: weixin
      
server.port: 8185